parameters: 
    buildConfiguration: 'Release'

steps: 
- task: DotNetCoreCLI@2
  displayName: 'Build the project -${{ parameters.buildConfiguration}}'
  inputs: 
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration }}' #  parameters is used to define inputs and ${{}} is used to read the input
  inputs:
    command: 'publish'
    projets: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} -- output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    zipAfterPublish : true
